# name: Deploy

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# on:
#   workflow_dispatch:

# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       - name: Deploy using ssh
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: 22
#           script: |
#             cd /var/www/myWebSite/
#             git pull origin main
#             git status
#             docker container stop my-web-site
#             docker container rm my-web-site
#             docker image rm my-web-site
#             docker build -t my-web-site .
#             docker run -d --name my-web-site -p 8080:80 my-web-site